[package]
name = "amp-common"
description = "Rust libraries shared across Amphitheatre components and libraries"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://amphitheatre.app"
repository = "https://github.com/amphitheatre-app/common"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
base64 = "0.21.0"
k8s-openapi = { version = "0.16.0", features = ["schemars", "v1_24"] }
serde = { version = "1.0", features = ["derive"] }
utoipa = { version = "3" }
